#'  downstream results formatting that tabulates limma output yielding
#'   1 gene name per entrezid with pvalues and other quantified information
#'   generated by limma
#' @param kexp        a KallistoExperiment or SummarizedExperiment-like object 
#' @param design      a design matrix with 2nd coefficient as one to test
#' @param p.cutoff    where to set the p-value cutoff for plots, etc. (0.05)
#' @param fold.cutoff where to set the log2-FC cutoff for plots, etc. (1==2x)
#' @param read.cutoff minimum read coverage (estimated) for a gene bundle 
#' @param topheat     how many bundles to include in the cluster heatmaps? (100)
#' @param species     which species? (Homo.sapiens; FIX: get from transcriptome)
#' 
#' @import edgeR 
#' @import limma
#' @import ReactomePA 
#' @import clusterProfiler
#' @import Homo.sapiens
#' @import Mus.musculus
#' @importFrom matrixStats rowSds 
#' 


message("Fitting bundles...")
  res <- fitBundles(kexp, design, bundleID="entrezid", read.cutoff=read.cutoff)
  res$top <- with(res, topTable(fit, coef=2, p=p.cutoff, n=nrow(kexp)))
  res$top <- res$top[ abs(res$top$logFC) >= fold.cutoff, ] ## per SEQC
  topGenes <- rownames(res$top)

  ## match species to map top genes to Entrez IDs 
  message("Matching species...")
  library(species, character.only=TRUE)
  topGenes <- topGenes[topGenes %in% keys(get(species), "ENTREZID")]


features(NS)[features(NS)$entrezid %in% topGenes]->NSTop
